package ru.pearx.libmc;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import java.util.Collections;

/*
 * Created by mrAppleXZ on 10.07.17 21:39.
 */
@Mod(modid = PXLMC.MODID, version = PXLMC.VERSION, acceptedMinecraftVersions = "", name = PXLMC.NAME)
public class PXLMC
{
    public static final String NAME = "PearXLib MC";
    public static final String MODID = "pxlmc";
    public static final String VERSION = "@VERSION@";

    @Mod.EventHandler
    public static void preInit(FMLPreInitializationEvent e)
    {
        ModMetadata data = e.getModMetadata();
        data.url = "https://minecraft.curseforge.com/projects/pearxlib-mc";
        data.authorList = Collections.singletonList("mrAppleXZ");
        data.autogenerated = false;
        data.description = "A common library for all MC mods by PearX Team.";
        data.version = VERSION;
        data.modId = MODID;
        data.name = NAME;
    }
}
